import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const router = useRouter();

  // useEffect(() => {
  //   router.push("https://42feedback.vercel.app/"), [];
  // }, []);

  return (
    <>
      <Head>
        <title>42Feedback-migration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>URLを変更しました。以後こちらのサイトをご利用ください。</p>
        <Link href={"https://42feedback.vercel.app/"}>
          https://42feedback.vercel.app/
        </Link>
        <p>こちらのページは、2月24日(金)13:00に削除します。</p>
      </main>
    </>
  );
}
